# Generated by Django 3.2.6 on 2021-08-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=125, null=True, verbose_name='时间')),
                ('P1', models.FloatField(default=None, null=True)),
                ('P2', models.FloatField(default=None, null=True)),
                ('P3', models.FloatField(default=None, null=True)),
                ('P4', models.FloatField(default=None, null=True)),
                ('P5', models.FloatField(default=None, null=True)),
                ('P6', models.FloatField(default=None, null=True)),
                ('P7', models.FloatField(default=None, null=True)),
                ('P8', models.FloatField(default=None, null=True)),
                ('P9', models.FloatField(default=None, null=True)),
                ('P10', models.FloatField(default=None, null=True)),
                ('P11', models.FloatField(default=None, null=True)),
                ('P12', models.FloatField(default=None, null=True)),
                ('P13', models.FloatField(default=None, null=True)),
                ('P14', models.FloatField(default=None, null=True)),
                ('P15', models.FloatField(default=None, null=True)),
                ('P16', models.FloatField(default=None, null=True)),
                ('P17', models.FloatField(default=None, null=True)),
                ('P18', models.FloatField(default=None, null=True)),
                ('P19', models.FloatField(default=None, null=True)),
                ('P20', models.FloatField(default=None, null=True)),
                ('P21', models.FloatField(default=None, null=True)),
                ('P22', models.FloatField(default=None, null=True)),
                ('P23', models.FloatField(default=None, null=True)),
                ('P24', models.FloatField(default=None, null=True)),
                ('P25', models.FloatField(default=None, null=True)),
                ('P26', models.FloatField(default=None, null=True)),
                ('P27', models.FloatField(default=None, null=True)),
                ('P28', models.FloatField(default=None, null=True)),
                ('P29', models.FloatField(default=None, null=True)),
                ('P30', models.FloatField(default=None, null=True)),
                ('P31', models.FloatField(default=None, null=True)),
                ('P32', models.FloatField(default=None, null=True)),
                ('P33', models.FloatField(default=None, null=True)),
                ('P34', models.FloatField(default=None, null=True)),
                ('P35', models.FloatField(default=None, null=True)),
                ('P36', models.FloatField(default=None, null=True)),
                ('P37', models.FloatField(default=None, null=True)),
                ('P38', models.FloatField(default=None, null=True)),
                ('P39', models.FloatField(default=None, null=True)),
                ('P40', models.FloatField(default=None, null=True)),
                ('P41', models.FloatField(default=None, null=True)),
                ('P42', models.FloatField(default=None, null=True)),
                ('P43', models.FloatField(default=None, null=True)),
                ('P44', models.FloatField(default=None, null=True)),
                ('P45', models.FloatField(default=None, null=True)),
                ('P46', models.FloatField(default=None, null=True)),
                ('P47', models.FloatField(default=None, null=True)),
                ('P48', models.FloatField(default=None, null=True)),
                ('P49', models.FloatField(default=None, null=True)),
                ('P50', models.FloatField(default=None, null=True)),
            ],
            options={
                'db_table': 'test_data',
            },
        ),
    ]
